services:
  order-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
      - ./order-service/migrations/001_create_orders.sql:/docker-entrypoint-initdb.d/001_create_orders.sql

  payment-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
      - ./payment-service/migrations/001_create_payments.sql:/docker-entrypoint-initdb.d/001_create_payments.sql

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    environment:
      PAYMENT_DB_DSN: postgres://postgres:postgres@payment-db:5432/payment_db?sslmode=disable
      PAYMENT_GRPC_PORT: "9091"
    ports:
      - "9091:9091"
    depends_on:
      - payment-db

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    environment:
      ORDER_DB_DSN: postgres://postgres:postgres@order-db:5432/order_db?sslmode=disable
      ORDER_PORT: "8080"
      ORDER_GRPC_PORT: "9090"
      PAYMENT_GRPC_ADDR: payment-service:9091
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - order-db
      - payment-service

volumes:
  order_db_data:
  payment_db_data:
